debug: false
trace: false

server:
  ssl:
    bundle: "demo"
  port: 443

logging:
  level:
    root: "info"
    org.springframework.web: "info"
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: "info"
    o.apache.tomcat.util.net.NioEndpoint.certificate: "info"
    org.hibernate: "info"
    hu.bruzsa: "debug"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

spring:
  output:
    ansi:
      enabled: detect
  security:
    user:
      name: "asdf1234"
      password: "lfsdjflksakdfjskdlfjsdkfjs21L"
  mvc:
    problemdetails:
      enabled: true
  ssl:
    bundle:
      pem:
        demo:
          reload-on-update: true
          keystore:
            certificate: "certs/ssl3.laci.my/certs/fullchain.pem"
            private-key: "certs/ssl3.laci.my/certs/domain.key"